/* automatically generated by rust-bindgen 0.57.0 */

pub const IO_USB_MAX_ENDPOINTS: u32 = 6;
pub const IO_HID_EP_LENGTH: u32 = 50;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const __bool_true_false_are_defined: u32 = 1;
pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2X: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 31;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __WORDSIZE: u32 = 32;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 0;
pub const __WORDSIZE32_SIZE_ULONG: u32 = 0;
pub const __WORDSIZE32_PTRDIFF_LONG: u32 = 0;
pub const __NO_LONG_DOUBLE_MATH: u32 = 1;
pub const __LONG_DOUBLE_USES_FLOAT128: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C2X: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const __TIMESIZE: u32 = 32;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 0;
pub const __STATFS_MATCHES_STATFS64: u32 = 0;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i32 = -2147483648;
pub const INT_FAST32_MIN: i32 = -2147483648;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u32 = 2147483647;
pub const INT_FAST32_MAX: u32 = 2147483647;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: u32 = 4294967295;
pub const UINT_FAST32_MAX: u32 = 4294967295;
pub const INTPTR_MIN: i32 = -2147483648;
pub const INTPTR_MAX: u32 = 2147483647;
pub const UINTPTR_MAX: u32 = 4294967295;
pub const PTRDIFF_MIN: i32 = -2147483648;
pub const PTRDIFF_MAX: u32 = 2147483647;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: u32 = 4294967295;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const CX_OK: u32 = 0;
pub const CX_CARRY: u32 = 4294967073;
pub const CX_LOCKED: u32 = 4294967169;
pub const CX_UNLOCKED: u32 = 4294967170;
pub const CX_NOT_LOCKED: u32 = 4294967171;
pub const CX_NOT_UNLOCKED: u32 = 4294967172;
pub const CX_INTERNAL_ERROR: u32 = 4294967173;
pub const CX_INVALID_PARAMETER_SIZE: u32 = 4294967174;
pub const CX_INVALID_PARAMETER_VALUE: u32 = 4294967175;
pub const CX_INVALID_PARAMETER: u32 = 4294967176;
pub const CX_NOT_INVERTIBLE: u32 = 4294967177;
pub const CX_OVERFLOW: u32 = 4294967178;
pub const CX_MEMORY_FULL: u32 = 4294967179;
pub const CX_NO_RESIDUE: u32 = 4294967180;
pub const CX_EC_INFINITE_POINT: u32 = 4294967105;
pub const CX_EC_INVALID_POINT: u32 = 4294967202;
pub const CX_EC_INVALID_CURVE: u32 = 4294967203;
pub const CX_AES_BLOCK_SIZE: u32 = 16;
pub const CX_BN_WORD_ALIGNEMENT: u32 = 16;
pub const CX_BN_FLAG_UNSET: u32 = 128;
pub const CX_DES_BLOCK_SIZE: u32 = 8;
pub const CX_MAX_DOMAIN_LENGTH: u32 = 66;
pub const CX_ECCINFO_PARITY_ODD: u32 = 1;
pub const CX_ECCINFO_xGTn: u32 = 2;
pub const CX_LAST: u32 = 1;
pub const CX_SIG_MODE: u32 = 2;
pub const CX_MASK_SIGCRYPT: u32 = 6;
pub const CX_ENCRYPT: u32 = 4;
pub const CX_DECRYPT: u32 = 0;
pub const CX_SIGN: u32 = 6;
pub const CX_VERIFY: u32 = 2;
pub const CX_MASK_PAD: u32 = 56;
pub const CX_PAD_NONE: u32 = 0;
pub const CX_PAD_ISO9797M1: u32 = 8;
pub const CX_PAD_ISO9797M2: u32 = 16;
pub const CX_PAD_PKCS1_1o5: u32 = 24;
pub const CX_PAD_PKCS1_PSS: u32 = 32;
pub const CX_PAD_PKCS1_OAEP: u32 = 40;
pub const CX_MASK_CHAIN: u32 = 448;
pub const CX_CHAIN_ECB: u32 = 0;
pub const CX_CHAIN_CBC: u32 = 64;
pub const CX_CHAIN_CTR: u32 = 128;
pub const CX_CHAIN_CFB: u32 = 192;
pub const CX_CHAIN_OFB: u32 = 256;
pub const CX_MASK_ECC_VARIANT: u32 = 448;
pub const CX_NO_CANONICAL: u32 = 64;
pub const CX_MASK_RND: u32 = 3584;
pub const CX_RND_PRNG: u32 = 512;
pub const CX_RND_TRNG: u32 = 1024;
pub const CX_RND_RFC6979: u32 = 1536;
pub const CX_RND_PROVIDED: u32 = 2048;
pub const CX_MASK_EC: u32 = 28672;
pub const CX_ECDH_POINT: u32 = 4096;
pub const CX_ECDH_X: u32 = 8192;
pub const CX_ECSCHNORR_ISO14888_XY: u32 = 12288;
pub const CX_ECSCHNORR_ISO14888_X: u32 = 16384;
pub const CX_ECSCHNORR_BSI03111: u32 = 20480;
pub const CX_ECSCHNORR_LIBSECP: u32 = 24576;
pub const CX_ECSCHNORR_Z: u32 = 28672;
pub const CX_NO_REINIT: u32 = 32768;
pub const APPLICATION_FLAG_MAIN: u32 = 1;
pub const APPLICATION_FLAG_BOLOS_UPGRADE: u32 = 2;
pub const APPLICATION_FLAG_SIGNED: u32 = 4;
pub const APPLICATION_FLAG_BOLOS_UX: u32 = 8;
pub const APPLICATION_FLAG_DERIVE_MASTER: u32 = 16;
pub const APPLICATION_FLAG_SHARED_NVRAM: u32 = 32;
pub const APPLICATION_FLAG_GLOBAL_PIN: u32 = 64;
pub const APPLICATION_FLAG_DEBUG: u32 = 128;
pub const APPLICATION_FLAG_AUTOBOOT: u32 = 256;
pub const APPLICATION_FLAG_BOLOS_SETTINGS: u32 = 512;
pub const APPLICATION_FLAG_CUSTOM_CA: u32 = 1024;
pub const APPLICATION_FLAG_LIBRARY: u32 = 2048;
pub const APPLICATION_FLAG_NO_RUN: u32 = 4096;
pub const APPLICATION_FLAG_ISSUER: u32 = 16384;
pub const APPLICATION_FLAG_ENABLED: u32 = 32768;
pub const APPLICATION_FLAG_AEM_PIN: u32 = 8;
pub const APPLICATION_FLAG_NEG_MASK: u32 = 4294901760;
pub const TARGET_ID: u32 = 823132164;
pub const ERR_IOL_RANGE: u32 = 4096;
pub const ERR_TSK_RANGE: u32 = 8192;
pub const ERR_CRY_RANGE: u32 = 12288;
pub const ERR_PAR_RANGE: u32 = 16384;
pub const ERR_SEC_RANGE: u32 = 20480;
pub const ERR_APD_RANGE: u32 = 24576;
pub const ERR_MUI_RANGE: u32 = 40960;
pub const ERR_APP_RANGE_01: u32 = 45056;
pub const ERR_APP_RANGE_02: u32 = 49152;
pub const ERR_APP_RANGE_03: u32 = 53248;
pub const ERR_APP_RANGE_04: u32 = 57344;
pub const ERR_GEN_SUB_01: u32 = 256;
pub const ERR_GEN_SUB_02: u32 = 512;
pub const ERR_GEN_SUB_03: u32 = 768;
pub const ERR_GEN_SUB_04: u32 = 1024;
pub const ERR_GEN_SUB_05: u32 = 1280;
pub const ERR_GEN_SUB_06: u32 = 1536;
pub const ERR_GEN_SUB_07: u32 = 1792;
pub const ERR_GEN_SUB_08: u32 = 2048;
pub const ERR_GEN_SUB_09: u32 = 2304;
pub const ERR_GEN_SUB_0D: u32 = 3328;
pub const ERR_GEN_SUB_0E: u32 = 3584;
pub const ERR_IOL_OFW: u32 = 4352;
pub const ERR_IOL_HDR: u32 = 4608;
pub const ERR_IOL_STA: u32 = 4864;
pub const ERR_IOL_RST: u32 = 5120;
pub const ERR_TSK_STC: u32 = 8448;
pub const ERR_TSK_OWN: u32 = 8704;
pub const ERR_TSK_OFW: u32 = 8960;
pub const ERR_CRY_LEN: u32 = 12544;
pub const ERR_CRY_VAL: u32 = 12800;
pub const ERR_PAR_LEN: u32 = 16640;
pub const ERR_PAR_VAL: u32 = 16896;
pub const ERR_SEC_APP: u32 = 20736;
pub const ERR_SEC_CRC: u32 = 20992;
pub const ERR_SEC_CHK: u32 = 21248;
pub const ERR_SEC_KEY: u32 = 21504;
pub const ERR_SEC_PIN: u32 = 21760;
pub const ERR_SEC_SCP: u32 = 22016;
pub const ERR_SEC_SIG: u32 = 22272;
pub const ERR_SEC_MEM: u32 = 22528;
pub const ERR_SEC_STA: u32 = 22784;
pub const ERR_APD_CLA: u32 = 28160;
pub const ERR_APD_INS: u32 = 27904;
pub const ERR_APD_HDR: u32 = 25856;
pub const ERR_APD_STA: u32 = 26112;
pub const ERR_APD_LEN: u32 = 26368;
pub const ERR_APD_DAT: u32 = 26624;
pub const SWO_SUCCESS: u32 = 36864;
pub const EXCEPTION: u32 = 1;
pub const INVALID_PARAMETER: u32 = 2;
pub const EXCEPTION_SECURITY: u32 = 3;
pub const INVALID_STATE: u32 = 4;
pub const EXCEPTION_IO_RESET: u32 = 5;
pub const NOT_ENOUGH_SPACE: u32 = 6;
pub const EXCEPTION_OVERFLOW: u32 = 7;
pub const INVALID_CRC: u32 = 8;
pub const INVALID_CHECKSUM: u32 = 9;
pub const INVALID_COUNTER: u32 = 10;
pub const NOT_SUPPORTED: u32 = 11;
pub const TIMEOUT: u32 = 12;
pub const EXCEPTION_PIC: u32 = 13;
pub const EXCEPTION_APPEXIT: u32 = 14;
pub const EXCEPTION_IO_OVERFLOW: u32 = 15;
pub const EXCEPTION_IO_HEADER: u32 = 16;
pub const EXCEPTION_IO_STATE: u32 = 17;
pub const EXCEPTION_CXPORT: u32 = 18;
pub const EXCEPTION_SYSTEM: u32 = 19;
pub const OS_PARSE_BERTLV_OFFSET_COMPARE_WITH_BUFFER: u32 = 2147483648;
pub const OS_PARSE_BERTLV_OFFSET_GET_LENGTH: u32 = 1073741824;
pub const CX_HASH_MAX_BLOCK_COUNT: u32 = 65535;
pub const CX_RIPEMD160_SIZE: u32 = 20;
pub const CX_SHA224_SIZE: u32 = 28;
pub const CX_SHA256_SIZE: u32 = 32;
pub const CX_SHA384_SIZE: u32 = 48;
pub const CX_SHA512_SIZE: u32 = 64;
pub const ROWS: u32 = 8;
pub const COLS1024: u32 = 16;
pub const SIZE1024: u32 = 128;
pub const CX_CRC16_INIT: u32 = 65535;
pub const _STRING_H: u32 = 1;
pub const _BITS_TYPES_LOCALE_T_H: u32 = 1;
pub const _BITS_TYPES___LOCALE_T_H: u32 = 1;
pub const _STRINGS_H: u32 = 1;
pub const MAX_TICKER_LEN: u32 = 12;
pub const ADDRESS_LENGTH: u32 = 20;
pub const INT256_LENGTH: u32 = 32;
pub const WEI_TO_ETHER: u32 = 18;
pub const SELECTOR_SIZE: u32 = 4;
pub const PARAMETER_LENGTH: u32 = 32;
pub const RUN_APPLICATION: u32 = 1;
pub const PLUGIN_ID_LENGTH: u32 = 30;
pub type size_t = cty::c_uint;
pub type wchar_t = cty::c_uint;
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: cty::c_longlong,
    pub __clang_max_align_nonce2: f64,
}
pub type __u_char = cty::c_uchar;
pub type __u_short = cty::c_ushort;
pub type __u_int = cty::c_uint;
pub type __u_long = cty::c_ulong;
pub type __int8_t = cty::c_schar;
pub type __uint8_t = cty::c_uchar;
pub type __int16_t = cty::c_short;
pub type __uint16_t = cty::c_ushort;
pub type __int32_t = cty::c_int;
pub type __uint32_t = cty::c_uint;
pub type __int64_t = cty::c_longlong;
pub type __uint64_t = cty::c_ulonglong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = cty::c_longlong;
pub type __u_quad_t = cty::c_ulonglong;
pub type __intmax_t = cty::c_longlong;
pub type __uintmax_t = cty::c_ulonglong;
pub type __dev_t = __uint64_t;
pub type __uid_t = cty::c_uint;
pub type __gid_t = cty::c_uint;
pub type __ino_t = cty::c_ulong;
pub type __ino64_t = __uint64_t;
pub type __mode_t = cty::c_uint;
pub type __nlink_t = cty::c_uint;
pub type __off_t = cty::c_long;
pub type __off64_t = __int64_t;
pub type __pid_t = cty::c_int;
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [cty::c_int; 2usize],
}
pub type __clock_t = cty::c_long;
pub type __rlim_t = cty::c_ulong;
pub type __rlim64_t = __uint64_t;
pub type __id_t = cty::c_uint;
pub type __time_t = cty::c_long;
pub type __useconds_t = cty::c_uint;
pub type __suseconds_t = cty::c_long;
pub type __daddr_t = cty::c_int;
pub type __key_t = cty::c_int;
pub type __clockid_t = cty::c_int;
pub type __timer_t = *mut cty::c_void;
pub type __blksize_t = cty::c_long;
pub type __blkcnt_t = cty::c_long;
pub type __blkcnt64_t = __int64_t;
pub type __fsblkcnt_t = cty::c_ulong;
pub type __fsblkcnt64_t = __uint64_t;
pub type __fsfilcnt_t = cty::c_ulong;
pub type __fsfilcnt64_t = __uint64_t;
pub type __fsword_t = cty::c_int;
pub type __ssize_t = cty::c_int;
pub type __syscall_slong_t = cty::c_long;
pub type __syscall_ulong_t = cty::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut cty::c_char;
pub type __intptr_t = cty::c_int;
pub type __socklen_t = cty::c_uint;
pub type __sig_atomic_t = cty::c_int;
pub type __time64_t = __int64_t;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = cty::c_schar;
pub type int_fast16_t = cty::c_int;
pub type int_fast32_t = cty::c_int;
pub type int_fast64_t = cty::c_longlong;
pub type uint_fast8_t = cty::c_uchar;
pub type uint_fast16_t = cty::c_uint;
pub type uint_fast32_t = cty::c_uint;
pub type uint_fast64_t = cty::c_ulonglong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type cx_err_t = u32;
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct cx_aes_key_s {
    pub size: size_t,
    pub keys: [u8; 32usize],
}
pub type cx_aes_key_t = cx_aes_key_s;
extern "C" {
    pub fn cx_aes_set_key_hw(key: *const cx_aes_key_t, mode: u32) -> cx_err_t;
}
extern "C" {
    pub fn cx_aes_reset_hw();
}
extern "C" {
    pub fn cx_aes_block_hw(inblock: *const cty::c_uchar, outblock: *mut cty::c_uchar) -> cx_err_t;
}
pub type cx_bn_t = u32;
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct cx_bn_mont_ctx_t {
    pub n: cx_bn_t,
    pub h: cx_bn_t,
}
extern "C" {
    pub fn cx_bn_lock(word_nbytes: size_t, flags: u32) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_unlock() -> u32;
}
extern "C" {
    pub fn cx_bn_is_locked() -> bool;
}
extern "C" {
    pub fn cx_bn_locked() -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_alloc(x: *mut cx_bn_t, nbytes: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_alloc_init(
        x: *mut cx_bn_t,
        nbytes: size_t,
        value: *const u8,
        value_nbytes: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_destroy(x: *mut cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_nbytes(x: cx_bn_t, nbytes: *mut size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_init(x: cx_bn_t, value: *const u8, value_nbytes: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_rand(x: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_copy(a: cx_bn_t, b: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_set_u32(x: cx_bn_t, n: u32) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_get_u32(x: cx_bn_t, n: *mut u32) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_export(x: cx_bn_t, bytes: *mut u8, nbytes: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_cmp(a: cx_bn_t, b: cx_bn_t, diff: *mut cty::c_int) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_cmp_u32(a: cx_bn_t, b: u32, diff: *mut cty::c_int) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_is_odd(n: cx_bn_t, odd: *mut bool) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_xor(r: cx_bn_t, a: cx_bn_t, b: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_or(r: cx_bn_t, a: cx_bn_t, b: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_and(r: cx_bn_t, a: cx_bn_t, b: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_tst_bit(x: cx_bn_t, pos: u32, set: *mut bool) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_set_bit(x: cx_bn_t, pos: u32) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_clr_bit(x: cx_bn_t, pos: u32) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_shr(x: cx_bn_t, n: u32) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_shl(x: cx_bn_t, n: u32) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_cnt_bits(n: cx_bn_t, nbits: *mut u32) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_add(r: cx_bn_t, a: cx_bn_t, b: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_sub(r: cx_bn_t, a: cx_bn_t, b: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_mul(r: cx_bn_t, a: cx_bn_t, b: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_mod_add(r: cx_bn_t, a: cx_bn_t, b: cx_bn_t, n: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_mod_sub(r: cx_bn_t, a: cx_bn_t, b: cx_bn_t, n: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_mod_mul(r: cx_bn_t, a: cx_bn_t, b: cx_bn_t, n: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_reduce(r: cx_bn_t, d: cx_bn_t, n: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_mod_sqrt(bn_r: cx_bn_t, bn_a: cx_bn_t, bn_n: cx_bn_t, sign: u32) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_mod_pow_bn(r: cx_bn_t, a: cx_bn_t, e: cx_bn_t, n: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_mod_pow(r: cx_bn_t, a: cx_bn_t, e: *const u8, e_len: u32, n: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_mod_pow2(r: cx_bn_t, a: cx_bn_t, e: *const u8, e_len: u32, n: cx_bn_t)
        -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_mod_invert_nprime(r: cx_bn_t, a: cx_bn_t, n: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_mod_u32_invert(r: cx_bn_t, a: u32, n: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_mont_alloc(ctx: *mut cx_bn_mont_ctx_t, length: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_mont_init(ctx: *mut cx_bn_mont_ctx_t, n: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_mont_init2(ctx: *mut cx_bn_mont_ctx_t, n: cx_bn_t, h: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_mont_to_montgomery(x: cx_bn_t, z: cx_bn_t, ctx: *const cx_bn_mont_ctx_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_mont_from_montgomery(
        z: cx_bn_t,
        x: cx_bn_t,
        ctx: *const cx_bn_mont_ctx_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_mont_mul(
        r: cx_bn_t,
        a: cx_bn_t,
        b: cx_bn_t,
        ctx: *const cx_bn_mont_ctx_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_mont_pow(
        r: cx_bn_t,
        a: cx_bn_t,
        e: *const u8,
        e_len: u32,
        ctx: *const cx_bn_mont_ctx_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_mont_pow_bn(
        r: cx_bn_t,
        a: cx_bn_t,
        e: cx_bn_t,
        ctx: *const cx_bn_mont_ctx_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_mont_invert_nprime(r: cx_bn_t, a: cx_bn_t, ctx: *const cx_bn_mont_ctx_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_is_prime(n: cx_bn_t, prime: *mut bool) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_next_prime(n: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_bn_rng(bn_r: cx_bn_t, bn_n: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_crc32_hw(buf: *const cty::c_void, len: size_t) -> u32;
}
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct cx_des_key_s {
    pub size: u8,
    pub keys: [u8; 24usize],
}
pub type cx_des_key_t = cx_des_key_s;
extern "C" {
    pub fn cx_des_set_key_hw(keys: *const cx_des_key_t, mode: u32) -> cx_err_t;
}
extern "C" {
    pub fn cx_des_reset_hw();
}
extern "C" {
    pub fn cx_des_block_hw(inblock: *const cty::c_uchar, outblock: *mut cty::c_uchar);
}
pub const CX_CURVE_NONE: cx_curve_e = 0;
pub const CX_CURVE_WEIERSTRASS_START: cx_curve_e = 32;
pub const CX_CURVE_SECP256K1: cx_curve_e = 33;
pub const CX_CURVE_SECP256R1: cx_curve_e = 34;
pub const CX_CURVE_SECP384R1: cx_curve_e = 35;
pub const CX_CURVE_SECP521R1: cx_curve_e = 36;
pub const CX_CURVE_BrainPoolP256T1: cx_curve_e = 49;
pub const CX_CURVE_BrainPoolP256R1: cx_curve_e = 50;
pub const CX_CURVE_BrainPoolP320T1: cx_curve_e = 51;
pub const CX_CURVE_BrainPoolP320R1: cx_curve_e = 52;
pub const CX_CURVE_BrainPoolP384T1: cx_curve_e = 53;
pub const CX_CURVE_BrainPoolP384R1: cx_curve_e = 54;
pub const CX_CURVE_BrainPoolP512T1: cx_curve_e = 55;
pub const CX_CURVE_BrainPoolP512R1: cx_curve_e = 56;
pub const CX_CURVE_BLS12_381_G1: cx_curve_e = 57;
pub const CX_CURVE_FRP256V1: cx_curve_e = 65;
pub const CX_CURVE_Stark256: cx_curve_e = 81;
pub const CX_CURVE_WEIERSTRASS_END: cx_curve_e = 111;
pub const CX_CURVE_TWISTED_EDWARDS_START: cx_curve_e = 112;
pub const CX_CURVE_Ed25519: cx_curve_e = 113;
pub const CX_CURVE_Ed448: cx_curve_e = 114;
pub const CX_CURVE_TWISTED_EDWARDS_END: cx_curve_e = 127;
pub const CX_CURVE_MONTGOMERY_START: cx_curve_e = 128;
pub const CX_CURVE_Curve25519: cx_curve_e = 129;
pub const CX_CURVE_Curve448: cx_curve_e = 130;
pub const CX_CURVE_MONTGOMERY_END: cx_curve_e = 143;
pub type cx_curve_e = cty::c_uchar;
pub use self::cx_curve_e as cx_curve_t;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_curve_weierstrass_s {
    pub curve: cx_curve_t,
    pub bit_size: cty::c_uint,
    pub length: cty::c_uint,
    pub a: *const u8,
    pub b: *const u8,
    pub p: *const u8,
    pub Gx: *const u8,
    pub Gy: *const u8,
    pub n: *const u8,
    pub h: *const u8,
    pub Hn: *const u8,
    pub Hp: *const u8,
}
impl Default for cx_curve_weierstrass_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type cx_curve_weierstrass_t = cx_curve_weierstrass_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_curve_twisted_edwards_s {
    pub curve: cx_curve_t,
    pub bit_size: cty::c_uint,
    pub length: cty::c_uint,
    pub a: *const u8,
    pub b: *const u8,
    pub p: *const u8,
    pub Gx: *const u8,
    pub Gy: *const u8,
    pub n: *const u8,
    pub h: *const u8,
    pub Hn: *const u8,
    pub Hp: *const u8,
}
impl Default for cx_curve_twisted_edwards_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type cx_curve_twisted_edwards_t = cx_curve_twisted_edwards_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_curve_montgomery_s {
    pub curve: cx_curve_t,
    pub bit_size: cty::c_uint,
    pub length: cty::c_uint,
    pub a: *const u8,
    pub b: *const u8,
    pub p: *const u8,
    pub Gx: *const u8,
    pub Gy: *const u8,
    pub n: *const u8,
    pub h: *const u8,
    pub Hn: *const u8,
    pub Hp: *const u8,
}
impl Default for cx_curve_montgomery_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type cx_curve_montgomery_t = cx_curve_montgomery_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_curve_domain_s {
    pub curve: cx_curve_t,
    pub bit_size: cty::c_uint,
    pub length: cty::c_uint,
    pub a: *const u8,
    pub b: *const u8,
    pub p: *const u8,
    pub Gx: *const u8,
    pub Gy: *const u8,
    pub n: *const u8,
    pub h: *const u8,
    pub Hn: *const u8,
    pub Hp: *const u8,
}
impl Default for cx_curve_domain_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type cx_curve_domain_t = cx_curve_domain_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_ec_point_s {
    pub curve: cx_curve_t,
    pub x: cx_bn_t,
    pub y: cx_bn_t,
    pub z: cx_bn_t,
}
impl Default for cx_ec_point_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type cx_ecpoint_t = cx_ec_point_s;
pub const CX_CURVE_PARAM_NONE: cx_curve_dom_param_s = 0;
pub const CX_CURVE_PARAM_A: cx_curve_dom_param_s = 1;
pub const CX_CURVE_PARAM_B: cx_curve_dom_param_s = 2;
pub const CX_CURVE_PARAM_Field: cx_curve_dom_param_s = 3;
pub const CX_CURVE_PARAM_Gx: cx_curve_dom_param_s = 4;
pub const CX_CURVE_PARAM_Gy: cx_curve_dom_param_s = 5;
pub const CX_CURVE_PARAM_Order: cx_curve_dom_param_s = 6;
pub const CX_CURVE_PARAM_Cofactor: cx_curve_dom_param_s = 7;
pub type cx_curve_dom_param_s = cty::c_uchar;
pub use self::cx_curve_dom_param_s as cx_curve_dom_param_t;
extern "C" {
    pub fn cx_ecdomain_size(curve: cx_curve_t, length: *mut size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecdomain_parameters_length(cv: cx_curve_t, length: *mut size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecdomain_parameter(
        cv: cx_curve_t,
        id: cx_curve_dom_param_t,
        p: *mut u8,
        p_len: u32,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecdomain_parameter_bn(
        cv: cx_curve_t,
        id: cx_curve_dom_param_t,
        p: cx_bn_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecdomain_generator(cv: cx_curve_t, Gx: *mut u8, Gy: *mut u8, len: size_t)
        -> cx_err_t;
}
extern "C" {
    pub fn cx_ecdomain_generator_bn(cv: cx_curve_t, P: *mut cx_ecpoint_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_alloc(P: *mut cx_ecpoint_t, cv: cx_curve_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_destroy(P: *mut cx_ecpoint_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_init(
        P: *mut cx_ecpoint_t,
        x: *const u8,
        x_len: size_t,
        y: *const u8,
        y_len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_init_bn(P: *mut cx_ecpoint_t, x: cx_bn_t, y: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_export(
        P: *const cx_ecpoint_t,
        x: *mut u8,
        x_len: size_t,
        y: *mut u8,
        y_len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_export_bn(
        P: *const cx_ecpoint_t,
        x: *mut cx_bn_t,
        y: *mut cx_bn_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_compress(
        P: *const cx_ecpoint_t,
        xy_compressed: *mut u8,
        xy_compressed_len: size_t,
        sign: *mut u32,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_decompress(
        P: *mut cx_ecpoint_t,
        xy_compressed: *const u8,
        xy_compressed_len: size_t,
        sign: u32,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_add(
        R: *mut cx_ecpoint_t,
        P: *const cx_ecpoint_t,
        Q: *const cx_ecpoint_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_neg(P: *mut cx_ecpoint_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_rnd_scalarmul(P: *mut cx_ecpoint_t, k: *const u8, k_len: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_rnd_scalarmul_bn(P: *mut cx_ecpoint_t, bn_k: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_rnd_fixed_scalarmul(
        P: *mut cx_ecpoint_t,
        k: *const u8,
        k_len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_scalarmul(P: *mut cx_ecpoint_t, k: *const u8, k_len: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_scalarmul_bn(P: *mut cx_ecpoint_t, bn_k: cx_bn_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_double_scalarmul(
        R: *mut cx_ecpoint_t,
        P: *mut cx_ecpoint_t,
        Q: *mut cx_ecpoint_t,
        k: *const u8,
        k_len: size_t,
        r: *const u8,
        r_len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_double_scalarmul_bn(
        R: *mut cx_ecpoint_t,
        P: *mut cx_ecpoint_t,
        Q: *mut cx_ecpoint_t,
        bn_k: cx_bn_t,
        bn_r: cx_bn_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_cmp(
        P: *const cx_ecpoint_t,
        Q: *const cx_ecpoint_t,
        is_equal: *mut bool,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_is_on_curve(R: *const cx_ecpoint_t, is_on_curve: *mut bool) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecpoint_is_at_infinity(R: *const cx_ecpoint_t, is_infinite: *mut bool) -> cx_err_t;
}
extern "C" {
    pub fn cx_trng_get_random_data(buf: *mut u8, size: size_t);
}
extern "C" {
    pub fn cx_trng_selftest();
}
extern "C" {
    pub fn cx_trng_init();
}
pub type uint64bits_t = u64;
pub const ERR_GEN_ID_01: generic_identifiers = 1;
pub const ERR_GEN_ID_02: generic_identifiers = 2;
pub const ERR_GEN_ID_03: generic_identifiers = 3;
pub const ERR_GEN_ID_04: generic_identifiers = 4;
pub const ERR_GEN_ID_05: generic_identifiers = 5;
pub const ERR_GEN_ID_06: generic_identifiers = 6;
pub const ERR_GEN_ID_07: generic_identifiers = 7;
pub const ERR_GEN_ID_08: generic_identifiers = 8;
pub const ERR_GEN_ID_09: generic_identifiers = 9;
pub const ERR_GEN_ID_0A: generic_identifiers = 10;
pub const ERR_GEN_ID_0B: generic_identifiers = 11;
pub const ERR_GEN_ID_0C: generic_identifiers = 12;
pub const ERR_GEN_ID_0D: generic_identifiers = 13;
pub const ERR_GEN_ID_0E: generic_identifiers = 14;
pub const ERR_GEN_ID_0F: generic_identifiers = 15;
pub const ERR_GEN_ID_10: generic_identifiers = 16;
pub const ERR_GEN_ID_11: generic_identifiers = 17;
pub const ERR_GEN_ID_12: generic_identifiers = 18;
pub const ERR_GEN_ID_13: generic_identifiers = 19;
pub const ERR_GEN_ID_14: generic_identifiers = 20;
pub const ERR_GEN_ID_15: generic_identifiers = 21;
pub const ERR_GEN_ID_16: generic_identifiers = 22;
pub const ERR_GEN_ID_17: generic_identifiers = 23;
pub const ERR_GEN_ID_18: generic_identifiers = 24;
pub const ERR_GEN_ID_19: generic_identifiers = 25;
pub const ERR_GEN_ID_1A: generic_identifiers = 26;
pub const ERR_GEN_ID_1B: generic_identifiers = 27;
pub const ERR_GEN_ID_1C: generic_identifiers = 28;
pub const ERR_GEN_ID_1D: generic_identifiers = 29;
pub const ERR_GEN_ID_1E: generic_identifiers = 30;
pub const ERR_GEN_ID_1F: generic_identifiers = 31;
pub const ERR_GEN_ID_20: generic_identifiers = 32;
pub const ERR_GEN_ID_21: generic_identifiers = 33;
pub const ERR_GEN_ID_22: generic_identifiers = 34;
pub const ERR_GEN_ID_23: generic_identifiers = 35;
pub const ERR_GEN_ID_24: generic_identifiers = 36;
pub const ERR_GEN_ID_25: generic_identifiers = 37;
pub const ERR_GEN_ID_26: generic_identifiers = 38;
pub const ERR_GEN_ID_27: generic_identifiers = 39;
pub const ERR_GEN_ID_28: generic_identifiers = 40;
pub const ERR_GEN_ID_29: generic_identifiers = 41;
pub const ERR_GEN_ID_2A: generic_identifiers = 42;
pub const ERR_GEN_ID_2B: generic_identifiers = 43;
pub type generic_identifiers = cty::c_uchar;
pub type exception_t = cty::c_ushort;
pub type try_context_t = try_context_s;
pub type jmp_buf = [cty::c_uint; 10usize];
extern "C" {
    pub fn longjmp(__jmpb: *mut cty::c_uint, __retval: cty::c_int);
}
extern "C" {
    pub fn setjmp(__jmpb: *mut cty::c_uint) -> cty::c_int;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct try_context_s {
    pub jmp_buf: jmp_buf,
    pub previous: *mut try_context_t,
    pub ex: exception_t,
}
impl Default for try_context_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
extern "C" {
    pub fn try_context_get() -> *mut try_context_t;
}
extern "C" {
    pub fn try_context_set(context: *mut try_context_t) -> *mut try_context_t;
}
extern "C" {
    pub fn os_longjmp(exception: cty::c_uint);
}
extern "C" {
    pub fn os_parse_bertlv(
        mem: *mut cty::c_uchar,
        mem_len: cty::c_uint,
        tlv_instance_offset: *mut cty::c_uint,
        tag: cty::c_uint,
        offset: cty::c_uint,
        buffer: *mut *mut cty::c_void,
        maxlength: cty::c_uint,
    ) -> cty::c_uint;
}
pub const CX_NONE: cx_md_e = 0;
pub const CX_RIPEMD160: cx_md_e = 1;
pub const CX_SHA224: cx_md_e = 2;
pub const CX_SHA256: cx_md_e = 3;
pub const CX_SHA384: cx_md_e = 4;
pub const CX_SHA512: cx_md_e = 5;
pub const CX_KECCAK: cx_md_e = 6;
pub const CX_SHA3: cx_md_e = 7;
pub const CX_GROESTL: cx_md_e = 8;
pub const CX_BLAKE2B: cx_md_e = 9;
pub const CX_SHAKE128: cx_md_e = 10;
pub const CX_SHAKE256: cx_md_e = 11;
pub const CX_SHA3_256: cx_md_e = 12;
pub const CX_SHA3_512: cx_md_e = 13;
pub type cx_md_e = cty::c_uchar;
pub use self::cx_md_e as cx_md_t;
pub type cx_hash_t = cx_hash_header_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_hash_info_t {
    pub md_type: cx_md_t,
    pub output_size: size_t,
    pub block_size: size_t,
    pub init_func: ::core::option::Option<unsafe extern "C" fn(ctx: *mut cx_hash_t) -> cx_err_t>,
    pub update_func: ::core::option::Option<
        unsafe extern "C" fn(ctx: *mut cx_hash_t, data: *const u8, len: size_t) -> cx_err_t,
    >,
    pub finish_func: ::core::option::Option<
        unsafe extern "C" fn(ctx: *mut cx_hash_t, digest: *mut u8) -> cx_err_t,
    >,
    pub init_ex_func: ::core::option::Option<
        unsafe extern "C" fn(ctx: *mut cx_hash_t, output_size: size_t) -> cx_err_t,
    >,
    pub output_size_func:
        ::core::option::Option<unsafe extern "C" fn(ctx: *const cx_hash_t) -> size_t>,
}
impl Default for cx_hash_info_t {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_hash_header_s {
    pub info: *const cx_hash_info_t,
    pub counter: u32,
}
impl Default for cx_hash_header_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
extern "C" {
    pub fn cx_hash_get_size(ctx: *const cx_hash_t) -> size_t;
}
extern "C" {
    pub fn cx_hash_no_throw(
        hash: *mut cx_hash_t,
        mode: u32,
        in_: *const u8,
        len: size_t,
        out: *mut u8,
        out_len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_hash_init(hash: *mut cx_hash_t, hash_id: cx_md_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_hash_init_ex(hash: *mut cx_hash_t, hash_id: cx_md_t, output_size: size_t)
        -> cx_err_t;
}
extern "C" {
    pub fn cx_hash_update(hash: *mut cx_hash_t, in_: *const u8, in_len: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_hash_final(hash: *mut cx_hash_t, digest: *mut u8) -> cx_err_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_ripemd160_s {
    pub header: cx_hash_header_s,
    pub blen: size_t,
    pub block: [u8; 64usize],
    pub acc: [u8; 20usize],
}
impl Default for cx_ripemd160_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type cx_ripemd160_t = cx_ripemd160_s;
extern "C" {
    pub fn cx_ripemd160_init_no_throw(hash: *mut cx_ripemd160_t) -> cx_err_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_sha256_s {
    pub header: cx_hash_header_s,
    pub blen: size_t,
    pub block: [u8; 64usize],
    pub acc: [u8; 32usize],
}
impl Default for cx_sha256_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type cx_sha256_t = cx_sha256_s;
extern "C" {
    pub fn cx_sha224_init_no_throw(hash: *mut cx_sha256_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_sha256_init_no_throw(hash: *mut cx_sha256_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_hash_sha256(in_: *const u8, len: size_t, out: *mut u8, out_len: size_t) -> size_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_sha512_s {
    pub header: cx_hash_header_s,
    pub blen: size_t,
    pub block: [u8; 128usize],
    pub acc: [u8; 64usize],
}
impl Default for cx_sha512_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type cx_sha512_t = cx_sha512_s;
extern "C" {
    pub fn cx_sha384_init_no_throw(hash: *mut cx_sha512_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_sha512_init_no_throw(hash: *mut cx_sha512_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_hash_sha512(in_: *const u8, in_len: size_t, out: *mut u8, out_len: size_t) -> size_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_sha3_s {
    pub header: cx_hash_header_s,
    pub output_size: size_t,
    pub block_size: size_t,
    pub blen: size_t,
    pub block: [u8; 200usize],
    pub acc: [uint64bits_t; 25usize],
}
impl Default for cx_sha3_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type cx_sha3_t = cx_sha3_s;
extern "C" {
    pub fn cx_sha3_init_no_throw(hash: *mut cx_sha3_t, size: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_keccak_init_no_throw(hash: *mut cx_sha3_t, size: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_shake128_init_no_throw(hash: *mut cx_sha3_t, out_size: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_shake256_init_no_throw(hash: *mut cx_sha3_t, out_size: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_sha3_xof_init_no_throw(
        hash: *mut cx_sha3_t,
        size: size_t,
        out_length: size_t,
    ) -> cx_err_t;
}
pub const BLAKE2B_BLOCKBYTES: blake2b_constant = 128;
pub const BLAKE2B_OUTBYTES: blake2b_constant = 64;
pub const BLAKE2B_KEYBYTES: blake2b_constant = 64;
pub const BLAKE2B_SALTBYTES: blake2b_constant = 16;
pub const BLAKE2B_PERSONALBYTES: blake2b_constant = 16;
pub type blake2b_constant = cty::c_uchar;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct blake2b_state__ {
    pub h: [u64; 8usize],
    pub t: [u64; 2usize],
    pub f: [u64; 2usize],
    pub buf: [u8; 128usize],
    pub buflen: size_t,
    pub outlen: size_t,
    pub last_node: u8,
}
impl Default for blake2b_state__ {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type blake2b_state = blake2b_state__;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_blake2b_s {
    pub header: cx_hash_header_s,
    pub output_size: size_t,
    pub ctx: blake2b_state__,
}
impl Default for cx_blake2b_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type cx_blake2b_t = cx_blake2b_s;
extern "C" {
    pub fn cx_blake2b_init_no_throw(hash: *mut cx_blake2b_t, out_len: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_blake2b_init2_no_throw(
        hash: *mut cx_blake2b_t,
        out_len: size_t,
        salt: *mut u8,
        salt_len: size_t,
        perso: *mut u8,
        perso_len: size_t,
    ) -> cx_err_t;
}
pub type BitSequence = cty::c_uchar;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct hashState_s {
    pub chaining: [[u8; 16usize]; 8usize],
    pub block_counter: u64,
    pub hashlen: cty::c_uint,
    pub buffer: [BitSequence; 128usize],
    pub buf_ptr: cty::c_uint,
    pub columns: cty::c_uint,
    pub rounds: cty::c_uint,
    pub statesize: cty::c_uint,
}
impl Default for hashState_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type hashState = hashState_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_groestl_s {
    pub header: cx_hash_header_s,
    pub output_size: cty::c_uint,
    pub ctx: hashState_s,
}
impl Default for cx_groestl_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type cx_groestl_t = cx_groestl_s;
extern "C" {
    pub fn cx_groestl_init_no_throw(hash: *mut cx_groestl_t, size: size_t) -> cx_err_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_hmac_t {
    pub key: [u8; 128usize],
    pub hash_ctx: cx_hash_t,
}
impl Default for cx_hmac_t {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_hmac_ripemd160_t {
    pub key: [u8; 128usize],
    pub hash_ctx: cx_ripemd160_t,
}
impl Default for cx_hmac_ripemd160_t {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
extern "C" {
    pub fn cx_hmac_ripemd160_init_no_throw(
        hmac: *mut cx_hmac_ripemd160_t,
        key: *const u8,
        key_len: size_t,
    ) -> cx_err_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_hmac_sha256_t {
    pub key: [u8; 128usize],
    pub hash_ctx: cx_sha256_t,
}
impl Default for cx_hmac_sha256_t {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
extern "C" {
    pub fn cx_hmac_sha224_init(
        hmac: *mut cx_hmac_sha256_t,
        key: *const u8,
        key_len: cty::c_uint,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_hmac_sha256_init_no_throw(
        hmac: *mut cx_hmac_sha256_t,
        key: *const u8,
        key_len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_hmac_sha256(
        key: *const u8,
        key_len: size_t,
        in_: *const u8,
        len: size_t,
        mac: *mut u8,
        mac_len: size_t,
    ) -> size_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_hmac_sha512_t {
    pub key: [u8; 128usize],
    pub hash_ctx: cx_sha512_t,
}
impl Default for cx_hmac_sha512_t {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
extern "C" {
    pub fn cx_hmac_sha384_init(
        hmac: *mut cx_hmac_sha512_t,
        key: *const u8,
        key_len: cty::c_uint,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_hmac_sha512_init_no_throw(
        hmac: *mut cx_hmac_sha512_t,
        key: *const u8,
        key_len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_hmac_sha512(
        key: *const u8,
        key_len: size_t,
        in_: *const u8,
        len: size_t,
        mac: *mut u8,
        mac_len: size_t,
    ) -> size_t;
}
extern "C" {
    pub fn cx_hmac_no_throw(
        hmac: *mut cx_hmac_t,
        mode: u32,
        in_: *const u8,
        len: size_t,
        mac: *mut u8,
        mac_len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_hmac_init(
        hmac: *mut cx_hmac_t,
        hash_id: cx_md_t,
        key: *const u8,
        key_len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_hmac_update(hmac: *mut cx_hmac_t, in_: *const u8, in_len: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_hmac_final(ctx: *mut cx_hmac_t, out: *mut u8, out_len: *mut size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_pbkdf2_no_throw(
        md_type: cx_md_t,
        password: *const u8,
        passwordlen: size_t,
        salt: *mut u8,
        saltlen: size_t,
        iterations: u32,
        out: *mut u8,
        outLength: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_rng_no_throw(buffer: *mut u8, len: size_t);
}
pub type cx_rng_u32_range_randfunc_t = ::core::option::Option<unsafe extern "C" fn() -> u32>;
extern "C" {
    pub fn cx_rng_u32_range_func(a: u32, b: u32, randfunc: cx_rng_u32_range_randfunc_t) -> u32;
}
extern "C" {
    pub fn cx_rng_rfc6979(
        hash_id: cx_md_t,
        x: *const u8,
        x_len: size_t,
        h1: *const u8,
        h1_len: size_t,
        q: *const u8,
        q_len: size_t,
        out: *mut u8,
        out_len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_math_cmp_no_throw(
        a: *const u8,
        b: *const u8,
        length: size_t,
        diff: *mut cty::c_int,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_math_add_no_throw(r: *mut u8, a: *const u8, b: *const u8, len: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_math_sub_no_throw(r: *mut u8, a: *const u8, b: *const u8, len: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_math_mult_no_throw(r: *mut u8, a: *const u8, b: *const u8, len: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_math_addm_no_throw(
        r: *mut u8,
        a: *const u8,
        b: *const u8,
        m: *const u8,
        len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_math_subm_no_throw(
        r: *mut u8,
        a: *const u8,
        b: *const u8,
        m: *const u8,
        len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_math_multm_no_throw(
        r: *mut u8,
        a: *const u8,
        b: *const u8,
        m: *const u8,
        len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_math_modm_no_throw(
        v: *mut u8,
        len_v: size_t,
        m: *const u8,
        len_m: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_math_powm_no_throw(
        r: *mut u8,
        a: *const u8,
        e: *const u8,
        len_e: size_t,
        m: *const u8,
        len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_math_invprimem_no_throw(
        r: *mut u8,
        a: *const u8,
        m: *const u8,
        len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_math_invintm_no_throw(r: *mut u8, a: u32, m: *const u8, len: size_t) -> cx_err_t;
}
extern "C" {
    pub fn cx_math_is_prime_no_throw(r: *const u8, len: size_t, prime: *mut bool) -> cx_err_t;
}
extern "C" {
    pub fn cx_math_next_prime_no_throw(r: *mut u8, len: u32) -> cx_err_t;
}
extern "C" {
    pub fn cx_des_init_key_no_throw(
        rawkey: *const u8,
        key_len: size_t,
        key: *mut cx_des_key_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_des_iv_no_throw(
        key: *const cx_des_key_t,
        mode: u32,
        iv: *const u8,
        iv_len: size_t,
        in_: *const u8,
        in_len: size_t,
        out: *mut u8,
        out_len: *mut size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_des_no_throw(
        key: *const cx_des_key_t,
        mode: u32,
        in_: *const u8,
        in_len: size_t,
        out: *mut u8,
        out_len: *mut size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_des_enc_block(key: *const cx_des_key_t, inblock: *const u8, outblock: *mut u8);
}
extern "C" {
    pub fn cx_des_dec_block(key: *const cx_des_key_t, inblock: *const u8, outblock: *mut u8);
}
extern "C" {
    pub fn cx_aes_init_key_no_throw(
        rawkey: *const u8,
        key_len: size_t,
        key: *mut cx_aes_key_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_aes_iv_no_throw(
        key: *const cx_aes_key_t,
        mode: u32,
        iv: *const u8,
        iv_len: size_t,
        in_: *const u8,
        in_len: size_t,
        out: *mut u8,
        out_len: *mut size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_aes_no_throw(
        key: *const cx_aes_key_t,
        mode: u32,
        in_: *const u8,
        in_len: size_t,
        out: *mut u8,
        out_len: *mut size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_aes_enc_block(
        key: *const cx_aes_key_t,
        inblock: *const u8,
        outblock: *mut u8,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_aes_dec_block(
        key: *const cx_aes_key_t,
        inblock: *const u8,
        outblock: *mut u8,
    ) -> cx_err_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_ecfp_public_key_s {
    pub curve: cx_curve_t,
    pub W_len: size_t,
    pub W: [u8; 1usize],
}
impl Default for cx_ecfp_public_key_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_ecfp_private_key_s {
    pub curve: cx_curve_t,
    pub d_len: size_t,
    pub d: [u8; 1usize],
}
impl Default for cx_ecfp_private_key_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_ecfp_256_public_key_s {
    pub curve: cx_curve_t,
    pub W_len: size_t,
    pub W: [u8; 65usize],
}
impl Default for cx_ecfp_256_public_key_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_ecfp_256_private_key_s {
    pub curve: cx_curve_t,
    pub d_len: size_t,
    pub d: [u8; 32usize],
}
impl Default for cx_ecfp_256_private_key_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_ecfp_256_extended_private_key_s {
    pub curve: cx_curve_t,
    pub d_len: size_t,
    pub d: [u8; 64usize],
}
impl Default for cx_ecfp_256_extended_private_key_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type cx_ecfp_256_public_key_t = cx_ecfp_256_public_key_s;
pub type cx_ecfp_256_private_key_t = cx_ecfp_256_private_key_s;
pub type cx_ecfp_256_extended_private_key_t = cx_ecfp_256_extended_private_key_s;
pub type cx_ecfp_public_key_t = cx_ecfp_256_public_key_s;
pub type cx_ecfp_private_key_t = cx_ecfp_256_private_key_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_ecfp_384_public_key_s {
    pub curve: cx_curve_t,
    pub W_len: size_t,
    pub W: [u8; 97usize],
}
impl Default for cx_ecfp_384_public_key_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_ecfp_384_private_key_s {
    pub curve: cx_curve_t,
    pub d_len: size_t,
    pub d: [u8; 48usize],
}
impl Default for cx_ecfp_384_private_key_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type cx_ecfp_384_private_key_t = cx_ecfp_384_private_key_s;
pub type cx_ecfp_384_public_key_t = cx_ecfp_384_public_key_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_ecfp_512_public_key_s {
    pub curve: cx_curve_t,
    pub W_len: size_t,
    pub W: [u8; 129usize],
}
impl Default for cx_ecfp_512_public_key_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_ecfp_512_private_key_s {
    pub curve: cx_curve_t,
    pub d_len: size_t,
    pub d: [u8; 64usize],
}
impl Default for cx_ecfp_512_private_key_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_ecfp_512_extented_private_key_s {
    pub curve: cx_curve_t,
    pub d_len: size_t,
    pub d: [u8; 128usize],
}
impl Default for cx_ecfp_512_extented_private_key_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type cx_ecfp_512_public_key_t = cx_ecfp_512_public_key_s;
pub type cx_ecfp_512_private_key_t = cx_ecfp_512_private_key_s;
pub type cx_ecfp_512_extented_private_key_t = cx_ecfp_512_extented_private_key_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_ecfp_640_public_key_s {
    pub curve: cx_curve_t,
    pub W_len: size_t,
    pub W: [u8; 161usize],
}
impl Default for cx_ecfp_640_public_key_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cx_ecfp_640_private_key_s {
    pub curve: cx_curve_t,
    pub d_len: size_t,
    pub d: [u8; 80usize],
}
impl Default for cx_ecfp_640_private_key_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type cx_ecfp_640_public_key_t = cx_ecfp_640_public_key_s;
pub type cx_ecfp_640_private_key_t = cx_ecfp_640_private_key_s;
extern "C" {
    pub fn cx_ecfp_add_point_no_throw(
        curve: cx_curve_t,
        R: *mut u8,
        P: *const u8,
        Q: *const u8,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecfp_scalar_mult_no_throw(
        curve: cx_curve_t,
        P: *mut u8,
        k: *const u8,
        k_len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecfp_init_public_key_no_throw(
        curve: cx_curve_t,
        rawkey: *const u8,
        key_len: size_t,
        key: *mut cx_ecfp_public_key_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecfp_init_private_key_no_throw(
        curve: cx_curve_t,
        rawkey: *const u8,
        key_len: size_t,
        pvkey: *mut cx_ecfp_private_key_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecfp_generate_pair_no_throw(
        curve: cx_curve_t,
        pubkey: *mut cx_ecfp_public_key_t,
        privkey: *mut cx_ecfp_private_key_t,
        keepprivate: bool,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecfp_generate_pair2_no_throw(
        curve: cx_curve_t,
        pubkey: *mut cx_ecfp_public_key_t,
        privkey: *mut cx_ecfp_private_key_t,
        keepprivate: bool,
        hashID: cx_md_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_eddsa_get_public_key_no_throw(
        pvkey: *const cx_ecfp_private_key_t,
        hashID: cx_md_t,
        pukey: *mut cx_ecfp_public_key_t,
        a: *mut u8,
        a_len: size_t,
        h: *mut u8,
        h_len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_edwards_compress_point_no_throw(
        curve: cx_curve_t,
        p: *mut u8,
        p_len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_edwards_decompress_point_no_throw(
        curve: cx_curve_t,
        p: *mut u8,
        p_len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecdsa_sign_no_throw(
        pvkey: *const cx_ecfp_private_key_t,
        mode: u32,
        hashID: cx_md_t,
        hash: *const u8,
        hash_len: size_t,
        sig: *mut u8,
        sig_len: *mut size_t,
        info: *mut u32,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecdsa_verify_no_throw(
        pukey: *const cx_ecfp_public_key_t,
        hash: *const u8,
        hash_len: size_t,
        sig: *const u8,
        sig_len: size_t,
    ) -> bool;
}
extern "C" {
    pub fn cx_eddsa_sign_no_throw(
        pvkey: *const cx_ecfp_private_key_t,
        hashID: cx_md_t,
        hash: *const u8,
        hash_len: size_t,
        sig: *mut u8,
        sig_len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_eddsa_verify_no_throw(
        pukey: *const cx_ecfp_public_key_t,
        hashID: cx_md_t,
        hash: *const u8,
        hash_len: size_t,
        sig: *const u8,
        sig_len: size_t,
    ) -> bool;
}
extern "C" {
    pub fn cx_encode_coord(coord: *mut u8, len: cty::c_int, sign: cty::c_int);
}
extern "C" {
    pub fn cx_decode_coord(coord: *mut u8, len: cty::c_int) -> cty::c_int;
}
extern "C" {
    pub fn cx_ecschnorr_sign_no_throw(
        pvkey: *const cx_ecfp_private_key_t,
        mode: u32,
        hashID: cx_md_t,
        msg: *const u8,
        msg_len: size_t,
        sig: *mut u8,
        sig_len: *mut size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_ecschnorr_verify(
        pukey: *const cx_ecfp_public_key_t,
        mode: u32,
        hashID: cx_md_t,
        msg: *const u8,
        msg_len: size_t,
        sig: *const u8,
        sig_len: size_t,
    ) -> bool;
}
extern "C" {
    pub fn cx_ecdh_no_throw(
        pvkey: *const cx_ecfp_private_key_t,
        mode: u32,
        P: *const u8,
        P_len: size_t,
        secret: *mut u8,
        secret_len: size_t,
    ) -> cx_err_t;
}
extern "C" {
    pub fn cx_crc16(buffer: *const cty::c_void, len: size_t) -> u16;
}
extern "C" {
    pub fn cx_crc16_update(crc: u16, buffer: *const cty::c_void, len: size_t) -> u16;
}
extern "C" {
    pub fn memcpy(
        __dest: *mut cty::c_void,
        __src: *const cty::c_void,
        __n: cty::c_uint,
    ) -> *mut cty::c_void;
}
extern "C" {
    pub fn memmove(
        __dest: *mut cty::c_void,
        __src: *const cty::c_void,
        __n: cty::c_uint,
    ) -> *mut cty::c_void;
}
extern "C" {
    pub fn memccpy(
        __dest: *mut cty::c_void,
        __src: *const cty::c_void,
        __c: cty::c_int,
        __n: cty::c_uint,
    ) -> *mut cty::c_void;
}
extern "C" {
    pub fn memset(__s: *mut cty::c_void, __c: cty::c_int, __n: cty::c_uint) -> *mut cty::c_void;
}
extern "C" {
    pub fn memcmp(
        __s1: *const cty::c_void,
        __s2: *const cty::c_void,
        __n: cty::c_uint,
    ) -> cty::c_int;
}
extern "C" {
    pub fn memchr(__s: *const cty::c_void, __c: cty::c_int, __n: cty::c_uint) -> *mut cty::c_void;
}
extern "C" {
    pub fn strcpy(__dest: *mut cty::c_char, __src: *const cty::c_char) -> *mut cty::c_char;
}
extern "C" {
    pub fn strncpy(
        __dest: *mut cty::c_char,
        __src: *const cty::c_char,
        __n: cty::c_uint,
    ) -> *mut cty::c_char;
}
extern "C" {
    pub fn strcat(__dest: *mut cty::c_char, __src: *const cty::c_char) -> *mut cty::c_char;
}
extern "C" {
    pub fn strncat(
        __dest: *mut cty::c_char,
        __src: *const cty::c_char,
        __n: cty::c_uint,
    ) -> *mut cty::c_char;
}
extern "C" {
    pub fn strcmp(__s1: *const cty::c_char, __s2: *const cty::c_char) -> cty::c_int;
}
extern "C" {
    pub fn strncmp(
        __s1: *const cty::c_char,
        __s2: *const cty::c_char,
        __n: cty::c_uint,
    ) -> cty::c_int;
}
extern "C" {
    pub fn strcoll(__s1: *const cty::c_char, __s2: *const cty::c_char) -> cty::c_int;
}
extern "C" {
    pub fn strxfrm(
        __dest: *mut cty::c_char,
        __src: *const cty::c_char,
        __n: cty::c_uint,
    ) -> cty::c_uint;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct __locale_struct {
    pub __locales: [*mut __locale_data; 13usize],
    pub __ctype_b: *const cty::c_ushort,
    pub __ctype_tolower: *const cty::c_int,
    pub __ctype_toupper: *const cty::c_int,
    pub __names: [*const cty::c_char; 13usize],
}
impl Default for __locale_struct {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type __locale_t = *mut __locale_struct;
pub type locale_t = __locale_t;
extern "C" {
    pub fn strcoll_l(
        __s1: *const cty::c_char,
        __s2: *const cty::c_char,
        __l: locale_t,
    ) -> cty::c_int;
}
extern "C" {
    pub fn strxfrm_l(
        __dest: *mut cty::c_char,
        __src: *const cty::c_char,
        __n: size_t,
        __l: locale_t,
    ) -> size_t;
}
extern "C" {
    pub fn strdup(__s: *const cty::c_char) -> *mut cty::c_char;
}
extern "C" {
    pub fn strndup(__string: *const cty::c_char, __n: cty::c_uint) -> *mut cty::c_char;
}
extern "C" {
    pub fn strchr(__s: *const cty::c_char, __c: cty::c_int) -> *mut cty::c_char;
}
extern "C" {
    pub fn strrchr(__s: *const cty::c_char, __c: cty::c_int) -> *mut cty::c_char;
}
extern "C" {
    pub fn strcspn(__s: *const cty::c_char, __reject: *const cty::c_char) -> cty::c_uint;
}
extern "C" {
    pub fn strspn(__s: *const cty::c_char, __accept: *const cty::c_char) -> cty::c_uint;
}
extern "C" {
    pub fn strpbrk(__s: *const cty::c_char, __accept: *const cty::c_char) -> *mut cty::c_char;
}
extern "C" {
    pub fn strstr(__haystack: *const cty::c_char, __needle: *const cty::c_char)
        -> *mut cty::c_char;
}
extern "C" {
    pub fn strtok(__s: *mut cty::c_char, __delim: *const cty::c_char) -> *mut cty::c_char;
}
extern "C" {
    pub fn __strtok_r(
        __s: *mut cty::c_char,
        __delim: *const cty::c_char,
        __save_ptr: *mut *mut cty::c_char,
    ) -> *mut cty::c_char;
}
extern "C" {
    pub fn strtok_r(
        __s: *mut cty::c_char,
        __delim: *const cty::c_char,
        __save_ptr: *mut *mut cty::c_char,
    ) -> *mut cty::c_char;
}
extern "C" {
    pub fn strlen(__s: *const cty::c_char) -> cty::c_uint;
}
extern "C" {
    pub fn strnlen(__string: *const cty::c_char, __maxlen: size_t) -> size_t;
}
extern "C" {
    pub fn strerror(__errnum: cty::c_int) -> *mut cty::c_char;
}
extern "C" {
    #[link_name = "\u{1}__xpg_strerror_r"]
    pub fn strerror_r(
        __errnum: cty::c_int,
        __buf: *mut cty::c_char,
        __buflen: size_t,
    ) -> cty::c_int;
}
extern "C" {
    pub fn strerror_l(__errnum: cty::c_int, __l: locale_t) -> *mut cty::c_char;
}
extern "C" {
    pub fn bcmp(__s1: *const cty::c_void, __s2: *const cty::c_void, __n: cty::c_uint)
        -> cty::c_int;
}
extern "C" {
    pub fn bcopy(__src: *const cty::c_void, __dest: *mut cty::c_void, __n: size_t);
}
extern "C" {
    pub fn bzero(__s: *mut cty::c_void, __n: cty::c_uint);
}
extern "C" {
    pub fn index(__s: *const cty::c_char, __c: cty::c_int) -> *mut cty::c_char;
}
extern "C" {
    pub fn rindex(__s: *const cty::c_char, __c: cty::c_int) -> *mut cty::c_char;
}
extern "C" {
    pub fn ffs(__i: cty::c_int) -> cty::c_int;
}
extern "C" {
    pub fn ffsl(__l: cty::c_long) -> cty::c_int;
}
extern "C" {
    pub fn ffsll(__ll: cty::c_longlong) -> cty::c_int;
}
extern "C" {
    pub fn strcasecmp(__s1: *const cty::c_char, __s2: *const cty::c_char) -> cty::c_int;
}
extern "C" {
    pub fn strncasecmp(
        __s1: *const cty::c_char,
        __s2: *const cty::c_char,
        __n: cty::c_uint,
    ) -> cty::c_int;
}
extern "C" {
    pub fn strcasecmp_l(
        __s1: *const cty::c_char,
        __s2: *const cty::c_char,
        __loc: locale_t,
    ) -> cty::c_int;
}
extern "C" {
    pub fn strncasecmp_l(
        __s1: *const cty::c_char,
        __s2: *const cty::c_char,
        __n: size_t,
        __loc: locale_t,
    ) -> cty::c_int;
}
extern "C" {
    pub fn explicit_bzero(__s: *mut cty::c_void, __n: size_t);
}
extern "C" {
    pub fn strsep(
        __stringp: *mut *mut cty::c_char,
        __delim: *const cty::c_char,
    ) -> *mut cty::c_char;
}
extern "C" {
    pub fn strsignal(__sig: cty::c_int) -> *mut cty::c_char;
}
extern "C" {
    pub fn __stpcpy(__dest: *mut cty::c_char, __src: *const cty::c_char) -> *mut cty::c_char;
}
extern "C" {
    pub fn stpcpy(__dest: *mut cty::c_char, __src: *const cty::c_char) -> *mut cty::c_char;
}
extern "C" {
    pub fn __stpncpy(
        __dest: *mut cty::c_char,
        __src: *const cty::c_char,
        __n: size_t,
    ) -> *mut cty::c_char;
}
extern "C" {
    pub fn stpncpy(
        __dest: *mut cty::c_char,
        __src: *const cty::c_char,
        __n: cty::c_uint,
    ) -> *mut cty::c_char;
}
pub const CHAIN_KIND_ETHEREUM: chain_kind_e = 0;
pub const CHAIN_KIND_ETHEREUM_CLASSIC: chain_kind_e = 1;
pub const CHAIN_KIND_EXPANSE: chain_kind_e = 2;
pub const CHAIN_KIND_POA: chain_kind_e = 3;
pub const CHAIN_KIND_RSK: chain_kind_e = 4;
pub const CHAIN_KIND_UBIQ: chain_kind_e = 5;
pub const CHAIN_KIND_WANCHAIN: chain_kind_e = 6;
pub const CHAIN_KIND_KUSD: chain_kind_e = 7;
pub const CHAIN_KIND_PIRL: chain_kind_e = 8;
pub const CHAIN_KIND_AKROMA: chain_kind_e = 9;
pub const CHAIN_KIND_MUSICOIN: chain_kind_e = 10;
pub const CHAIN_KIND_CALLISTO: chain_kind_e = 11;
pub const CHAIN_KIND_ETHERSOCIAL: chain_kind_e = 12;
pub const CHAIN_KIND_ELLAISM: chain_kind_e = 13;
pub const CHAIN_KIND_ETHER1: chain_kind_e = 14;
pub const CHAIN_KIND_ETHERGEM: chain_kind_e = 15;
pub const CHAIN_KIND_ATHEIOS: chain_kind_e = 16;
pub const CHAIN_KIND_GOCHAIN: chain_kind_e = 17;
pub const CHAIN_KIND_MIX: chain_kind_e = 18;
pub const CHAIN_KIND_REOSC: chain_kind_e = 19;
pub const CHAIN_KIND_HPB: chain_kind_e = 20;
pub const CHAIN_KIND_TOMOCHAIN: chain_kind_e = 21;
pub const CHAIN_KIND_TOBALABA: chain_kind_e = 22;
pub const CHAIN_KIND_DEXON: chain_kind_e = 23;
pub const CHAIN_KIND_VOLTA: chain_kind_e = 24;
pub const CHAIN_KIND_EWC: chain_kind_e = 25;
pub const CHAIN_KIND_ARTIS_SIGMA1: chain_kind_e = 26;
pub const CHAIN_KIND_ARTIS_TAU1: chain_kind_e = 27;
pub const CHAIN_KIND_WEBCHAIN: chain_kind_e = 28;
pub const CHAIN_KIND_THUNDERCORE: chain_kind_e = 29;
pub const CHAIN_KIND_FLARE: chain_kind_e = 30;
pub const CHAIN_KIND_BSC: chain_kind_e = 31;
pub const CHAIN_KIND_SONGBIRD: chain_kind_e = 32;
pub type chain_kind_e = cty::c_uchar;
pub use self::chain_kind_e as chain_kind_t;
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct tokenDefinition_t {
    pub address: [u8; 20usize],
    pub ticker: [cty::c_char; 12usize],
    pub decimals: u8,
}
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct txInt256_t {
    pub value: [u8; 32usize],
    pub length: u8,
}
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct txContent_t {
    pub gasprice: txInt256_t,
    pub startgas: txInt256_t,
    pub value: txInt256_t,
    pub nonce: txInt256_t,
    pub chainID: txInt256_t,
    pub destination: [u8; 20usize],
    pub destinationLength: u8,
    pub v: [u8; 8usize],
    pub vLength: u8,
    pub dataPresent: bool,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct chain_config_s {
    pub coinName: [cty::c_char; 10usize],
    pub chainId: u64,
    pub kind: chain_kind_t,
}
impl Default for chain_config_s {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type chain_config_t = chain_config_s;
extern "C" {
    pub static HEXDIGITS: [cty::c_char; 17usize];
}
extern "C" {
    pub fn getEthAddressStringFromBinary(
        address: *mut u8,
        out: *mut cty::c_char,
        sha3Context: *mut cx_sha3_t,
        chainId: u64,
    );
}
extern "C" {
    pub fn getEthAddressFromKey(
        publicKey: *mut cx_ecfp_public_key_t,
        out: *mut u8,
        sha3Context: *mut cx_sha3_t,
    );
}
extern "C" {
    pub fn getEthDisplayableAddress(
        in_: *mut u8,
        out: *mut cty::c_char,
        out_len: size_t,
        sha3: *mut cx_sha3_t,
        chainId: u64,
    );
}
extern "C" {
    pub fn adjustDecimals(
        src: *mut cty::c_char,
        srcLength: u32,
        target: *mut cty::c_char,
        targetLength: u32,
        decimals: u8,
    ) -> bool;
}
extern "C" {
    pub fn uint256_to_decimal(
        value: *const u8,
        value_len: size_t,
        out: *mut cty::c_char,
        out_len: size_t,
    ) -> bool;
}
extern "C" {
    pub fn amountToString(
        amount: *const u8,
        amount_len: u8,
        decimals: u8,
        ticker: *const cty::c_char,
        out_buffer: *mut cty::c_char,
        out_buffer_size: u8,
    );
}
extern "C" {
    pub fn u64_to_string(src: u64, dst: *mut cty::c_char, dst_size: u8);
}
pub const ETH_PLUGIN_INTERFACE_VERSION_1: eth_plugin_interface_version_t = 1;
pub const ETH_PLUGIN_INTERFACE_VERSION_LATEST: eth_plugin_interface_version_t = 2;
pub type eth_plugin_interface_version_t = cty::c_uchar;
pub const ETH_PLUGIN_INIT_CONTRACT: eth_plugin_msg_t = 257;
pub const ETH_PLUGIN_PROVIDE_PARAMETER: eth_plugin_msg_t = 258;
pub const ETH_PLUGIN_FINALIZE: eth_plugin_msg_t = 259;
pub const ETH_PLUGIN_PROVIDE_TOKEN: eth_plugin_msg_t = 260;
pub const ETH_PLUGIN_QUERY_CONTRACT_ID: eth_plugin_msg_t = 261;
pub const ETH_PLUGIN_QUERY_CONTRACT_UI: eth_plugin_msg_t = 262;
pub const ETH_PLUGIN_CHECK_PRESENCE: eth_plugin_msg_t = 511;
pub type eth_plugin_msg_t = cty::c_ushort;
pub const ETH_PLUGIN_RESULT_ERROR: eth_plugin_result_t = 0;
pub const ETH_PLUGIN_RESULT_UNAVAILABLE: eth_plugin_result_t = 1;
pub const ETH_PLUGIN_RESULT_UNSUCCESSFUL: eth_plugin_result_t = 2;
pub const ETH_PLUGIN_RESULT_SUCCESSFUL: eth_plugin_result_t = 3;
pub const ETH_PLUGIN_RESULT_OK: eth_plugin_result_t = 4;
pub const ETH_PLUGIN_RESULT_OK_ALIAS: eth_plugin_result_t = 5;
pub const ETH_PLUGIN_RESULT_FALLBACK: eth_plugin_result_t = 6;
pub type eth_plugin_result_t = cty::c_uchar;
pub const ETH_UI_TYPE_AMOUNT_ADDRESS: eth_ui_type_t = 1;
pub const ETH_UI_TYPE_GENERIC: eth_ui_type_t = 2;
pub type eth_ui_type_t = cty::c_uchar;
pub type PluginCall =
    ::core::option::Option<unsafe extern "C" fn(arg1: cty::c_int, arg2: *mut cty::c_void)>;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ethPluginSharedRW_t {
    pub sha3: *mut cx_sha3_t,
}
impl Default for ethPluginSharedRW_t {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ethPluginSharedRO_t {
    pub txContent: *mut txContent_t,
}
impl Default for ethPluginSharedRO_t {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ethPluginInitContract_t {
    pub interfaceVersion: u8,
    pub result: u8,
    pub pluginSharedRW: *mut ethPluginSharedRW_t,
    pub pluginSharedRO: *mut ethPluginSharedRO_t,
    pub pluginContext: *mut u8,
    pub pluginContextLength: size_t,
    pub selector: *mut u8,
    pub dataSize: size_t,
    pub alias: *mut cty::c_char,
}
impl Default for ethPluginInitContract_t {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ethPluginProvideParameter_t {
    pub pluginSharedRW: *mut ethPluginSharedRW_t,
    pub pluginSharedRO: *mut ethPluginSharedRO_t,
    pub pluginContext: *mut u8,
    pub parameter: *mut u8,
    pub parameterOffset: u32,
    pub result: u8,
}
impl Default for ethPluginProvideParameter_t {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ethPluginFinalize_t {
    pub pluginSharedRW: *mut ethPluginSharedRW_t,
    pub pluginSharedRO: *mut ethPluginSharedRO_t,
    pub pluginContext: *mut u8,
    pub tokenLookup1: *mut u8,
    pub tokenLookup2: *mut u8,
    pub amount: *mut u8,
    pub address: *mut u8,
    pub uiType: u8,
    pub numScreens: u8,
    pub result: u8,
}
impl Default for ethPluginFinalize_t {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ethPluginProvideToken_t {
    pub pluginSharedRW: *mut ethPluginSharedRW_t,
    pub pluginSharedRO: *mut ethPluginSharedRO_t,
    pub pluginContext: *mut u8,
    pub token1: *mut tokenDefinition_t,
    pub token2: *mut tokenDefinition_t,
    pub additionalScreens: u8,
    pub result: u8,
}
impl Default for ethPluginProvideToken_t {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ethQueryContractID_t {
    pub pluginSharedRW: *mut ethPluginSharedRW_t,
    pub pluginSharedRO: *mut ethPluginSharedRO_t,
    pub pluginContext: *mut u8,
    pub name: *mut cty::c_char,
    pub nameLength: size_t,
    pub version: *mut cty::c_char,
    pub versionLength: size_t,
    pub result: u8,
}
impl Default for ethQueryContractID_t {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ethQueryContractUI_t {
    pub pluginSharedRW: *mut ethPluginSharedRW_t,
    pub pluginSharedRO: *mut ethPluginSharedRO_t,
    pub pluginContext: *mut u8,
    pub screenIndex: u8,
    pub title: *mut cty::c_char,
    pub titleLength: size_t,
    pub msg: *mut cty::c_char,
    pub msgLength: size_t,
    pub result: u8,
}
impl Default for ethQueryContractUI_t {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct __locale_data {
    pub _address: u8,
}
