---
name: Build and run tests using the SDK

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  build_ethereum_application:
    name: Build application using the reusable workflow
    uses: ./.github/workflows/_reusable_build_with_submodule_injection.yml
    with:
      app_repository: LedgerHQ/app-ethereum
      app_branch_name: develop
      upload_app_binaries_artifact: "ethereum_binaries"
      flags: "CAL_TEST_KEY=1 DOMAIN_NAME_TEST_KEY=1 SET_PLUGIN_TEST_KEY=1 NFT_TEST_KEY=1"

  ragger_ethereum_tests:
    name: Run ragger tests using the reusable workflow
    needs: build_ethereum_application
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@v1
    with:
      app_repository: LedgerHQ/app-ethereum
      app_branch_name: develop
      download_app_binaries_artifact: "ethereum_binaries"

  build_plugin_boilerplate_application:
    name: Build application using the reusable workflow
    uses: ./.github/workflows/_reusable_build_with_submodule_injection.yml
    with:
      app_repository: LedgerHQ/app-plugin-boilerplate
      app_branch_name: develop
      upload_app_binaries_artifact: "plugin_boilerplate_binaries"

  ragger_plugin_boilerplate_tests:
    name: Run ragger tests using the reusable workflow
    needs: build_plugin_boilerplate_application
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@v1
    with:
      app_repository: LedgerHQ/app-plugin-boilerplate
      app_branch_name: develop
      download_app_binaries_artifact: "plugin_boilerplate_binaries"
      additional_app_binaries_artifact: "ethereum_binaries"
      additional_app_binaries_artifact_dir: ./tests/.test_dependencies/ethereum/build
