---
name: Publish docs via GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout plugin-boilerplate
        uses: actions/checkout@v4
        with:
          path: ./app-plugin-boilerplate
          repository: LedgerHQ/app-plugin-boilerplate
          ref: develop

      - name: Configure Git Credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install requirements
        run: pip install -r docs/requirements.txt

      - name: Deploy docs
        run: |
          mkdocs gh-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
